
trigger:
- devel

jobs:
- job: 'SireLinux'
  pool:
    vmImage: 'Ubuntu-18.04'

  timeoutInMinutes: 180

  steps:
  - script: |
      cd docker/sire-devel-latest && docker build -f Dockerfile -t siremol/sire-devel:latest . && cd -
    displayName: 'Build Sire'
  - script: |
      cd docker/sire-test-devel && docker build -f Dockerfile -t siremol/sire-test-devel:latest . && cd -
    displayName: 'Run Sire tests'
  - script: |
      cd docker/sire-package-devel && docker build -f Dockerfile -t siremol/sire-package-devel:latest . && cd -
    displayName: 'Package Sire'
  - script: |
      # deploy the binary to an object store bucket identified by 'par_url'
      cd docker/sire-deploy-devel && docker build -f Dockerfile --build-arg par_url=$par_url . && cd -
      # now push the latest build to docker
      docker login -u $id -p $pswd
      docker push siremol/sire-devel:latest
    env:
      par_url: $(parURL)
      pswd: $(dockerPassword)
      id: $(dockerId)
    displayName: 'Deploy to siremol.org and docker'
  - script: |
      # finally create the Sire Conda package and upload to the Anaconda Cloud.
      cd docker/sire-conda && docker build -f Dockerfile --build-arg anaconda_token=$anaconda_token --build-arg par_url=$par_url . && cd -
    env:
      anaconda_token: $(anacondaToken)
      par_url: $(parURL)
    displayName: 'Create Conda package and upload to the Anaconda Cloud'
