package:
  name: sire
  version: VERSION

source:
    url: https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/hZ7irmpoxcr9EbjwDWHCPCWgZmbf1NxVIY8UISxPWxw/n/hugs/b/sire_releases/o/sire_conda_latest_linux.tar.bz2  # [linux]
  sha256: SHA256_LINUX  # [linux]
  url: https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/P_Z3QHRbqOigW4KmeojLJMdF6p_A2SGaA5A77ohMjSk/n/hugs/b/sire_releases/o/sire_conda_latest_osx.tar.bz2  # [osx]
  sha256: SHA256_OSX  # [osx]

build:
  number: BUILD
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python 3.7
    - boost
    - gsl
    - netcdf4
    - openmm
    - pyqt
    - tbb
    - tbb_devel
  run:
    - {{ pin_compatible('python') }}
    - boost
    - gsl
    - libcblas
    - libnetcdf
    - netcdf4
    - openmm
    - pyqt
    - qt
    - tbb
    - tbb_devel

test:
  imports:
    - Sire

about:
  home: https://github.com/michellab/Sire
  license: GPL-2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "An advanced, multiscale, molecular simulation framework."
  dev_url: https://github.com/michellab/Sire
  doc_url: https://siremol.org

extra:
  recipe-maintainers:
    - lohedges
    - chryswoods
