name: Build

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python-version: ["3.9"]
    environment:
      name: sire-build
    defaults:
      run:
        shell: pwsh
    env:
      SIRE_DONT_PHONEHOME: 1
      SIRE_SILENT_PHONEHOME: 1
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: sire_build
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true
      - name: Clone the devel branch
        run: git clone --single-branch https://github.com/michellab/Sire
        if: github.event_name != 'pull_request'
      - name: Clone the repository branch
        run: git clone -b ${{ github.head_ref }} --single-branch https://github.com/michellab/Sire
        if: github.event_name == 'pull_request'
      - name: Setup Conda
        run: mamba install -y -c conda-forge boa anaconda-client pip-requirements-parser
      - name: Where am I?
        run:
          Get-Location
      - name: What is here?
        run:
          ls ${{ github.workspace }}/Sire/actions
      - name: Update Conda recipe
        run:
          python ${{ github.workspace }}/Sire/actions/update_recipe.py
      - name: Build Conda package
        run: conda mambabuild -c conda-forge -c michellab ${{ github.workspace }}/Sire/recipes/sire
      - name: Upload Conda package
        run: python ${{ github.workspace }}/Sire/actions/upload_package.py
        env:
          SRC_DIR: ${{ github.workspace }}/Sire
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        if: github.event_name != 'pull_request'
