name: Build

on:
  push:
    branches: [ devel ]
    tags:
      - "*"
  pull_request:
    branches: [ devel ]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: sire_build
      - name: Clone the repository
        run: git clone https://github.com/michellab/Sire
      - name: Checkout the head branch if a pull request
        run: |
          cd Sire
          git checkout "$HEAD_BRANCH"
        env:
          HEAD_BRANCH: ${{ github.head_ref }}
        if: github.event_name == 'pull_request'
      - name: Setup Conda
        shell: bash -l {0}
        run: conda install -y conda-build anaconda-client
      - name: Update Conda recipe
        run: Sire/actions/update_recipe.sh "$GITHUB_WORKSPACE"/Sire
      - name: Build Conda package
        shell: bash -l {0}
        run: conda-build -c conda-forge -c michellab Sire/recipes/sire
      - name: Upload Conda package
        shell: bash -l {0}
        run: Sire/actions/upload_package.sh "$GITHUB_WORKSPACE"/Sire "$CONDA"
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        if: github.event_name != 'pull_request'
